# Generated by Django 6.0.5 on 2026-05-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
