# Generated by Django 6.0.5 on 2026-09-11 09:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_decodertype_alter_package_duration_months_and_more'),
        ('payments', '0005_remove_payment_payments_pa_order_r_546c18_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decoder_number', models.CharField(db_index=True, max_length=100)),
                ('months', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='decoder_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='packages.decodertype'),
        ),
        migrations.AddField(
            model_name='payment',
            name='total_decoders',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='payment',
            name='total_months',
            field=models.IntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['decoder_type', 'status'], name='pay_dtype_status_idx'),
        ),
        migrations.AddField(
            model_name='paymentitem',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_items', to='packages.package'),
        ),
        migrations.AddField(
            model_name='paymentitem',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.payment'),
        ),
        migrations.AddIndex(
            model_name='paymentitem',
            index=models.Index(fields=['decoder_number'], name='payitem_decoder_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentitem',
            index=models.Index(fields=['payment'], name='payitem_payment_idx'),
        ),
    ]
