# Generated by Django 6.0.5 on 2026-09-13 07:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_decodertype_alter_package_duration_months_and_more'),
        ('payments', '0006_paymentitem_payment_decoder_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('USSD', 'USSD Push'), ('CARD', 'Card Payment'), ('MOBILE', 'Mobile Money')], db_index=True, default='USSD', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method', 'status'], name='pay_method_status_idx'),
        ),
    ]
