# Generated by Django 6.0.5 on 2026-09-13 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0003_decodertype_alter_package_duration_months_and_more'),
        ('payments', '0006_paymentitem_payment_decoder_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecoderSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decoder_number', models.CharField(db_index=True, max_length=100)),
                ('months', models.IntegerField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACTIVE', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('decoder_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='packages.decodertype')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='packages.package')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='payments.payment')),
                ('payment_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='payments.paymentitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decoder_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='subscriptio_user_id_4bcc77_idx'), models.Index(fields=['decoder_number', 'status'], name='subscriptio_decoder_250b52_idx'), models.Index(fields=['expires_at', 'status'], name='subscriptio_expires_33c9ad_idx')],
            },
        ),
    ]
